version: '2'
services:
  dtu:
    build: "."
    environment:
      - MONGO_URL=mongodb://mongo/findMyStuffDB
    ports:
      - "4004:4004"
    depends_on:
      - mongo
    volumes:
      - .:/usr/local/app
  mongo:
    image: mongo:4.0
    ports:
      - "27016:27017"
    volumes:
      - ~/Downloads/dtu/db/:/data/db
      - ~/Downloads/dtu/dump/:/dump
